name: SmallRye Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: AdoptOpenJDK/install-jdk@v1
        name: set up jdk 11
        with:
          version: 11

      - name: Maven
        run: mvn -B formatter:validate install --file pom.xml

      - uses: actions/checkout@v2
        name: checkout smallrye-config
        with:
          repository: smallrye/smallrye-config
          path: smallrye-config

      - name: test with smallrye-config
        run: |
          cd smallrye-config
          mvn versions:update-parent -DallowSnapshots=true -N
          git diff pom.xml
          mvn install
